# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NotesmdCli < Formula
  desc ""
  homepage "https://github.com/Yakitrak/notesmd-cli"

  on_macos do
    url "https://github.com/Yakitrak/notesmd-cli/releases/download/v0.3.7/notesmd-cli_0.3.7_darwin_all.tar.gz"
    sha256 "b657c8b19c5fb6524136b3c47c10c3febffa9e48e8253313ea9f6f6fc32d6c72"

    define_method(:install) do
      bin.install "notesmd-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Yakitrak/notesmd-cli/releases/download/v0.3.7/notesmd-cli_0.3.7_linux_amd64.tar.gz"
      sha256 "f7e8f21b42f494d3c1af5d4f4f3b917922354289e4f5fddb7345c0750b3a9017"
      define_method(:install) do
        bin.install "notesmd-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Yakitrak/notesmd-cli/releases/download/v0.3.7/notesmd-cli_0.3.7_linux_arm64.tar.gz"
      sha256 "3867ab60156ffd9fd938981e55f8fcbccdf5837ed518b640059a42c0e2f39ab4"
      define_method(:install) do
        bin.install "notesmd-cli"
      end
    end
  end
end
