# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NotesmdCli < Formula
  desc ""
  homepage "https://github.com/Yakitrak/notesmd-cli"
  version "0.3.2"

  on_macos do
    url "https://github.com/Yakitrak/notesmd-cli/releases/download/v0.3.2/notesmd-cli_0.3.2_darwin_all.tar.gz"
    sha256 "3ff6188e8505ac72e4e4cd2ac69837da2f1a244117d50f5af2efbab9350fa06f"

    define_method(:install) do
      bin.install "notesmd-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Yakitrak/notesmd-cli/releases/download/v0.3.2/notesmd-cli_0.3.2_linux_amd64.tar.gz"
      sha256 "169911f03fa6e626ae55d3089fca8603c31a16da0a07f545890d685a8c2ef8e7"
      define_method(:install) do
        bin.install "notesmd-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Yakitrak/notesmd-cli/releases/download/v0.3.2/notesmd-cli_0.3.2_linux_arm64.tar.gz"
      sha256 "166c235be04e5dc3c24ce7ed4648f844fc9ccbafcb537542ec42c66d88d5f962"
      define_method(:install) do
        bin.install "notesmd-cli"
      end
    end
  end
end
