# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obs < Formula
  desc ""
  homepage "https://github.com/Yakitrak/obsidian-cli"
  version "0.9.0"

  on_macos do
    url "https://github.com/Yakitrak/obsidian-cli/releases/download/v0.9.0/obsidian-cli_0.9.0_darwin_all.tar.gz"
    sha256 "f2834035a5e713af81caa3b69e9dfaa36973f88c1e0b21abcd9e0065d1391eb4"

    def install
      bin.install "obsidian-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Yakitrak/obsidian-cli/releases/download/v0.9.0/obsidian-cli_0.9.0_linux_arm64.tar.gz"
      sha256 "9864c9f96bb2970dc185ec7448db71280a3d510f9aff8c714a06b4811b954093"

      def install
        bin.install "obs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Yakitrak/obsidian-cli/releases/download/v0.9.0/obsidian-cli_0.9.0_linux_amd64.tar.gz"
      sha256 "883421ff487d7b9453f1ab80a7ba44188b2b0c7aae10e74c7143b99335b75869"

      def install
        bin.install "obs"
      end
    end
  end
end
