# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obs < Formula
  desc ""
  homepage "https://github.com/Yakitrak/obsidian-cli"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Yakitrak/obsidian-cli/releases/download/v0.1.5/obsidian-cli_0.1.5_darwin_amd64.tar.gz"
      sha256 "c50b58798021ffc948f7a325593a3a11267a094ba948ef704fce645c2f6686ae"

      def install
        bin.install "obs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Yakitrak/obsidian-cli/releases/download/v0.1.5/obsidian-cli_0.1.5_darwin_arm64.tar.gz"
      sha256 "89ee1fb97acb3e5c30ddbf6dfaf7ff17c70579f6290f93513b12fecce494c377"

      def install
        bin.install "obs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Yakitrak/obsidian-cli/releases/download/v0.1.5/obsidian-cli_0.1.5_linux_arm64.tar.gz"
      sha256 "bb8b4673e4cb3915a40c568eeea329612cf20e103cd1ceccc99d305b4ee7bcc5"

      def install
        bin.install "obs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Yakitrak/obsidian-cli/releases/download/v0.1.5/obsidian-cli_0.1.5_linux_amd64.tar.gz"
      sha256 "c9ace85a49cc0efe345d855c71cacb1a42cf408ce04c06d8be7caf7ef706ddc5"

      def install
        bin.install "obs"
      end
    end
  end
end
