# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ObsidianCli < Formula
  desc ""
  homepage "https://github.com/Yakitrak/obsidian-cli"
  version "0.2.2"

  on_macos do
    url "https://github.com/Yakitrak/obsidian-cli/releases/download/v0.2.2/obsidian-cli_0.2.2_darwin_all.tar.gz"
    sha256 "81b40ceee3e1e7a4dde41634fa64c4a20431ff1f7b56f9d7379575a42896b1e0"

    def install
      bin.install "obsidian-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Yakitrak/obsidian-cli/releases/download/v0.2.2/obsidian-cli_0.2.2_linux_amd64.tar.gz"
      sha256 "0b96d76caa8cf1741db83ed8a9157700e67ad264702437981e6cefffd43d888d"
      def install
        bin.install "obsidian-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Yakitrak/obsidian-cli/releases/download/v0.2.2/obsidian-cli_0.2.2_linux_arm64.tar.gz"
      sha256 "a62d179701531266e174e3aa3ced4a7a6ca906a8a46a5d9c623dd6c34bb477af"
      def install
        bin.install "obsidian-cli"
      end
    end
  end
end
