# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ObsidianCli < Formula
  desc ""
  homepage "https://github.com/Yakitrak/obsidian-cli"
  version "0.1.7"

  on_macos do
    url "https://github.com/Yakitrak/obsidian-cli/releases/download/v0.1.7/obsidian-cli_0.1.7_darwin_all.tar.gz"
    sha256 "b63a99ba3c070c330f08aa0ef527f7609ec085c55a417a9ab4ece92c48c1a246"

    def install
      bin.install "obsidian-cli"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Yakitrak/obsidian-cli/releases/download/v0.1.7/obsidian-cli_0.1.7_linux_amd64.tar.gz"
        sha256 "7ad1de39123d0c385d364adfc6a3b084b7068231973ab43fed4282fc7dc1802b"

        def install
          bin.install "obsidian-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Yakitrak/obsidian-cli/releases/download/v0.1.7/obsidian-cli_0.1.7_linux_arm64.tar.gz"
        sha256 "222000445eb74deee02093a72c1996f6d780d2c80da4e9271b4af0567107aa44"

        def install
          bin.install "obsidian-cli"
        end
      end
    end
  end
end
